/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package itson.tune.presentacion;

/**
 *
 * @author Pride Factor Black
 */
public class FmrReproducirCancion extends javax.swing.JFrame {

    /**
     * Creates new form FmrReproducirCancion
     */
    public FmrReproducirCancion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVolver = new javax.swing.JButton();
        btnPaAtras = new javax.swing.JButton();
        btnPaLante = new javax.swing.JButton();
        btnPausar = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnVolver.png"))); // NOI18N
        btnVolver.setBorderPainted(false);
        btnVolver.setContentAreaFilled(false);
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        btnPaAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/skip_next_filled.png"))); // NOI18N
        btnPaAtras.setBorderPainted(false);
        btnPaAtras.setContentAreaFilled(false);
        btnPaAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(btnPaAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, -1, -1));

        btnPaLante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/skip_next_filled_derecha.png"))); // NOI18N
        btnPaLante.setBorderPainted(false);
        btnPaLante.setContentAreaFilled(false);
        getContentPane().add(btnPaLante, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 500, -1, -1));

        btnPausar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pausar.png"))); // NOI18N
        btnPausar.setBorderPainted(false);
        btnPausar.setContentAreaFilled(false);
        getContentPane().add(btnPausar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 500, -1, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PantallaReproducirCancion.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPaAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaAtrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPaAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FmrReproducirCancion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FmrReproducirCancion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FmrReproducirCancion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FmrReproducirCancion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FmrReproducirCancion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPaAtras;
    private javax.swing.JButton btnPaLante;
    private javax.swing.JButton btnPausar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel lblFondo;
    // End of variables declaration//GEN-END:variables
}
