/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import negocio.GestorMusica;

/**
 *
 * @author ramonsebastianzamudioayala
 */
public class MainApp extends javax.swing.JFrame {
    GestorMusica gestor;
    /**
     * Creates new form MainApp
     */
    public MainApp(GestorMusica gestor) {
        initComponents();
        this.gestor = gestor;
        setLocationRelativeTo(null);
        getContentPane().setBackground(new Color(25, 20,20));  
        
        jLabel1.setHorizontalAlignment(JLabel.CENTER);
        setLayout(new BorderLayout());
        add(jLabel1, BorderLayout.NORTH);
        add(jPanel1,BorderLayout.CENTER);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        crearPlaylist = new javax.swing.JButton();
        bibliotecaCanciones = new javax.swing.JButton();
        agregaCancion = new javax.swing.JButton();
        reproducirPlaylist = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(25, 20, 20));

        crearPlaylist.setText("Crear Playlist");
        crearPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearPlaylistActionPerformed(evt);
            }
        });

        bibliotecaCanciones.setText("Ver Biblioteca de Canciones");
        bibliotecaCanciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bibliotecaCancionesActionPerformed(evt);
            }
        });

        agregaCancion.setText("Agregar Cancion a Playlist");
        agregaCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregaCancionActionPerformed(evt);
            }
        });

        reproducirPlaylist.setText("Reproducir PlayList");
        reproducirPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reproducirPlaylistActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(reproducirPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregaCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bibliotecaCanciones, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crearPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(229, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(crearPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(bibliotecaCanciones, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(agregaCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(reproducirPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(29, 185, 84));
        jLabel1.setText("espotifai");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearPlaylistActionPerformed
        // TODO add your handling code here:
        String texto = JOptionPane.showInputDialog(
                this,
                "Nombre de la nueva playlis:",
                "Crear Playlist",
                JOptionPane.PLAIN_MESSAGE
        );
        gestor.crearNuevaPlaylist(texto);
    }//GEN-LAST:event_crearPlaylistActionPerformed

    private void bibliotecaCancionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bibliotecaCancionesActionPerformed
        // TODO add your handling code here:
        
        CatalogoCanciones catalogo = new CatalogoCanciones(gestor,null,ModoVentana.SOLO_MOSTRAR);
        catalogo.setVisible(true);
    }//GEN-LAST:event_bibliotecaCancionesActionPerformed

    private void agregaCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregaCancionActionPerformed
        // TODO add your handling code here:String playlist = JOptionPane.showInputDialog(
                
         String playlist = JOptionPane.showInputDialog(
                this,
                "Escribe el nombre de la playlist destino:",
                "Buscar Playlist",
                JOptionPane.PLAIN_MESSAGE
        );
        CatalogoCanciones catalogo = new CatalogoCanciones(gestor, playlist, ModoVentana.AGREGAR);
        catalogo.setVisible(true);
    }//GEN-LAST:event_agregaCancionActionPerformed

    private void reproducirPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reproducirPlaylistActionPerformed
        // TODO add your handling code here:
        String playlist = JOptionPane.showInputDialog(
                this,
                "Escribe el nombre de la playlist destino:",
                "Buscar Playlist",
                JOptionPane.PLAIN_MESSAGE
        );
        gestor.reproducirPlaylist(playlist);
    }//GEN-LAST:event_reproducirPlaylistActionPerformed
    
    
   /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GestorMusica gestor = new GestorMusica();
                new MainApp(gestor).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregaCancion;
    private javax.swing.JButton bibliotecaCanciones;
    private javax.swing.JButton crearPlaylist;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton reproducirPlaylist;
    // End of variables declaration//GEN-END:variables
}
